-- MySQL Script generated by MySQL Workbench
-- 2017年05月31日 星期三 15时46分23秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema phero
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `phero` ;

-- -----------------------------------------------------
-- Schema phero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phero` DEFAULT CHARACTER SET utf8 ;
USE `phero` ;

-- -----------------------------------------------------
-- Table `phero`.`Parent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`Parent` ;

CREATE TABLE IF NOT EXISTS `phero`.`Parent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `phero`.`Children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`Children` ;

CREATE TABLE IF NOT EXISTS `phero`.`Children` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `pid` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `phero`.`Mother`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`Mother` ;

CREATE TABLE IF NOT EXISTS `phero`.`Mother` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `phero`.`Marry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`Marry` ;

CREATE TABLE IF NOT EXISTS `phero`.`Marry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pid` INT NULL,
  `mid` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `phero`.`ParentInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`ParentInfo` ;

CREATE TABLE IF NOT EXISTS `phero`.`ParentInfo` (
  `pid` INT NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`pid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `phero`.`MotherInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `phero`.`MotherInfo` ;

CREATE TABLE IF NOT EXISTS `phero`.`MotherInfo` (
  `mid` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`mid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
