#!/usr/bin/php -q
<?php 
require "vendor/autoload.php";
use Phero\Command\UnitBuilder;
use Symfony\Component\Console\Application;
$application=new Application();
$UnitBuilder=new UnitBuilder();
$application->add($UnitBuilder);
$application->run();